name: main-tools
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release"
      - "development"
      - "feature/*"
jobs:
  build-git-semver:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.8
        with:
          # the path to the .env file (including file name)
          path: .github/workflows/variables/variable.env
          # whether to log the variables to output or not
          log-variables: true
          # whether to mask the variables as secrets or not
          mask-variables: false
      - name: Build git-semver
        run: |
          docker build -f ./Dockerfile . -t ghcr.io/${{ github.repository_owner }}/git-semver:${{ steps.dotenv.outputs.version }}
        shell: bash
        working-directory: ./src/git-semver
      - name: Test git-semver
        run: |
          next_version=$(docker run --rm ghcr.io/${{ github.repository_owner }}/git-semver:${{ steps.dotenv.outputs.version }} git-semver ${{ steps.dotenv.outputs.version }} ${{ github.ref_name }} ${{ github.sha }})
          echo "::set-output name=next_version::$(echo $next_version)"
        shell: bash
      - name: Push git-semver
        run: |
          echo ${{ env.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/git-semver:${{ steps.dotenv.outputs.version }}
        shell: bash